# ====================================
#  Poseidon | Diffusion Model Training
# ====================================
#
# ===== Cluster Configuration =====
#
Cluster:
  "account"  : ["bsmfc"]
  "cpus"     : [8]
  "gpus"     : [1]
  "partition": ["gpu"]
  "ram"      : ["60GB"]
  "time"     : ["48:00:00"]


# ===== Diffusion Training Configuration =====
#
Training Pipeline:

  config_wandb:
    "project": ["Poseidon-Training-Black-Sea-Shelf-Debugging"]
    "mode":    ["disabled"]

  config_problem:
    "model_checkpoint_name":    [null]
    "model_checkpoint_version": [null]
    "model_saving":             [False]
    "toy_problem":              [True]

  config_dataloader:
    "batch_size":      [1]
    "num_workers":     [0]
    "prefetch_factor": [null]
    "shuffle":         [[True, False, False]]
    "trajectory_size": [4]

  config_training:
    "blanket_neighbors":           [1]
    "steps_training":              [32]
    "steps_gradient_accumulation": [1]
    "steps_logging":               [1]
    "steps_validation":            [4]

  config_optimizer:
    "betas":         [[0.9, 0.999, 0.999]]
    "learning_rate": [0.001]
    "optimizer":     ["soap"]
    "weight_decay":  [0.0]

  config_scheduler:
    "scheduler": ["constant"]

  config_unet:
    "kernel_size":      [3]
    "mod_features":     [32]
    "ffn_scaling":      [2]
    "hid_blocks":       [[1, 1]]
    "hid_channels":     [[4, 8]]
    "attention_heads" : [{"-1": 1}]

  config_transformer:
    "hid_channels":     [16]
    "hid_blocks":       [4]
    "patch_size":       [2]
    "ffn_scaling":      [2]
    "attention_heads" : [1]

  config_siren:
      "features": [2]
      "n_layers": [1]
