# A configuration file for the training pipeline.

Training Pipeline:

  config_wandb:
    "project": ["Poseidon-Training-Big"]
    "mode": ["disabled"]

  config_problem:
    "toy_problem": [True]

  config_dataloader:
    "trajectory_size": [5]
    "batch_size": [2]
    "num_workers": [0]
    "prefetch_factor": [null]
    "shuffle": [[True, False, False]]

  config_training:
    "blanket_neighbors": [1]
    "steps_training": [2]
    "steps_gradient_accumulation": [2]

  config_optimizer:
    "optimizer": ["soap"]
    "learning_rate": [0.001, 0.0001]
    "weight_decay": [0]
    "betas": [[0.9, 0.999, 0.999]]

  config_scheduler:
    "scheduler": ["constant"]

  config_unet:
    "kernel_size": [3]
    "mod_features": [1]
    "hid_channels": [[32, 32, 32]]
    "hid_blocks": [[2, 2, 2]]
    "dropout": [null]

  config_siren:
      "features": [2]
      "n_layers": [1]

Cluster:
  "cpus"     : [4]
  "gpus"     : [1]
  "ram"      : ["60GB"]
  "time"     : ["00:30:00"]
  "partition": ["ia"]
  "account"  : ["bsmfc"]
