# A configuration file to launch multiple trainings

Training Pipeline:

  config_problem:
    "toy_problem": [True]

  config_dataloader:
    "trajectory_size": [5]
    "batch_size": [4]
    "num_workers": [0]
    "prefetch_factor": [null]
    "shuffle": [[True, False, False]]

  config_training:
    "blanket_neighbors": [1]
    "learning_rate": [0.0001]
    "weight_decay": [0.0]
    "number_epochs": [100]

  config_unet:
    "kernel_size": [3]
    "mod_features": [1]
    "hid_channels": [[32 ,32, 32]]
    "hid_blocks": [[1, 1, 1]]
    "dropout": [null]

  config_siren:
      "features": [6]
      "n_layers": [3]


Cluster:
  "cpus"     : [8]
  "gpus"     : [1]
  "ram"      : ["60GB"]
  "time"     : ["48:00:00"]
  "partition": ["gpu"]
  "account"  : ["bsmfc"]
