# ======================================
#  Poseidon | Diffusion Model Validation
# ======================================
#
# ===== Cluster Configuration =====
#
"account"  : ["bsmfc"]
"cpus"     : [2]
"gpus"     : [1]
"partition": ["gpu"]
"ram"      : ["60GB"]
"time"     : ["00:10:00"]
