# ======================================
#  Poseidon | Diffusion Model Validation
# ======================================
#
# ===== Cluster Configuration =====
#
"account"  : ["bsmfc"]
"cpus"     : [8]
"gpus"     : [1]
"partition": ["ia"]
"ram"      : ["60GB"]
"time"     : ["02:00:00"]
