[project]
name = "poseidon"
version = "0.0.0"
dependencies = [
  "bottleneck==1.4.0",
  "dask==2024.6.2",
  "einops==0.8.0",
  "netCDF4==1.7.0",
  "numcodecs==0.15.1",
  "numpy==1.26.3",
  "scipy==1.16.0",
  "torch==2.5.1",
  "torchvision==0.20.1",
  "tqdm==4.66.4",
  "wandb==0.19.8",
  "xarray==2024.6.0",
  "xformers==0.0.28.post3",
  "zarr==2.18.2",
]

[project.optional-dependencies]
all = [
  "cmocean==4.0.3",
  "dawgz==1.0.3",
  "ipykernel==6.29.5",
  "jupyterlab==4.2.2",
  "matplotlib==3.9.0",
  "pre-commit==3.7.1",
  "pytest==8.2.2",
  "ruff==0.4.8",
]

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120

[tool.ruff.lint]
extend-select = ["B", "I", "W"]
ignore = ["E731", "E741"]

[tool.ruff.lint.isort]
lines-between-types = 1
relative-imports-order = "closest-to-furthest"
section-order = ["future", "third-party", "first-party", "local-folder"]

[tool.ruff.format]
preview = true

[tool.setuptools.packages.find]
include = ["poseidon*"]
