# -------------------------------------------------------------
#
#        |
#       / \                 ESA - MITHO PROJECT
#      / _ \
#     |.o '.|      "GENERATIVE MODELS FOR HYPOXIA FORECASTING"
#     |'._.'|
#     |     |               by VICTOR MANGELEER
#   ,'|  |  |`.
#  /  |  |  |  \                2023-2024
#  |,-'--|--'-.|
#
# --------------------------------------------------------------
# https://eo4society.esa.int/projects/mitho/
#
# Documentation
# -------------
# A configuration file to be given to the main training script (__training.py)
#
config:

  # WandB
  "Project"             : ["ESA - Cluster (Diffusion with Metrics)"]
  "Mode"                : ["online"]

  # Data
  "Window (Inputs)"     : [1, 3, 7, 15, 30, 60, 90, 120, 150]
  "Window (Outputs)"    : [10]

  # Model
  "Scaling"             : [4]
  "Frequencies"         : [256]

  # Training
  "Diffusion Steps"     : [500]
  "Diffusion Scheduler" : [0.0125]
  "Diffusion Variance"  : [0.005]
  "Epochs"              : [1000]
  "Batch Size"          : [16]
  "Learning Rate"       : [0.0001, 0.00005]
  "Number of Workers"   : [2]

cluster:
  "Dawgz"    : True
  "CPUS"     : 2
  "GPUS"     : 2
  "RAM"      : "120GB"
  "TIME"     : "48:00:00"
  "PARTITION": "ia"
