# -------------------------------------------------------------
#
#        |
#       / \                 ESA - MITHO PROJECT
#      / _ \
#     |.o '.|      "GENERATIVE MODELS FOR HYPOXIA FORECASTING"
#     |'._.'|
#     |     |               by VICTOR MANGELEER
#   ,'|  |  |`.
#  /  |  |  |  \                2023-2024
#  |,-'--|--'-.|
#
# --------------------------------------------------------------
# https://eo4society.esa.int/projects/mitho/
#
# Documentation
# -------------
# A configuration file to be given to the main training script (__training.py)
#
config:

  # WandB
  "Project"             : "ESA - Local V3 (Diffusion)"
  "Mode"                : "online"

  # Data
  "Window (Inputs)"     : 3
  "Window (Outputs)"    : 10

  # Model
  "Scaling"             : 1
  "Frequencies"         : 32

  # Training
  "Diffusion Steps"     : 5
  "Diffusion Scheduler" : 0.0125
  "Diffusion Variance"  : 0.005
  "Epochs"              : 10
  "Batch Size"          : 16
  "Learning Rate"       : 0.0001
  "Number of Workers"   : 2

cluster:
  "Dawgz"    : False
  "CPUS"     : 2
  "GPUS"     : 1
  "RAM"      : "120GB"
  "TIME"     : "06:00:00"
  "PARTITION": "ia"
