# ======================================
#  Poseidon | Diffusion Model Validation
# ======================================
#
# ===== Cluster Configuration =====
#
"account"  : ["bsmfc"]
"cpus"     : [4]
"partition": ["batch"]
"ram"      : ["128GB"]
"time"     : ["02:00:00"]
